### ISSUE TITLE
Free RAM needs rounding on KVM Details

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#1505]
**Describe the bug**

**maas-ui version**
tip

**MAAS version**
development

**To Reproduce**
1. Visit KVM details on bolla

**Expected behavior**
Round to two places.

**Screenshots**
![image](https://user-images.githubusercontent.com/130286/91101837-09bf6600-e6bc-11ea-925f-c4b9330c32fc.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by Caleb-Ellis** [comment]
@squidsoup - oh wow this is a JS float calculation bug, as well as me trying to be clever when I shouldn't have. Instead of calculating `free` and passing that to the component, I've inferred `free` from `total` and `allocated` (`free = total - allocated`). In bolla's case this comes to `free = 15.6 - 12` which should be `3.6`, but JS gives the result `3.5999999999999996`. You can confirm by running `console.log(15.6 - 12)`.

Anyway I've updated the PR to use `formatBytes` directly and the correct result is actually 3.55. Goes to show how the margin for error can grow if you compound truncated values!

**Comment by Caleb-Ellis** [comment]
Fixed in #1489
