### ISSUE TITLE
PCI Tab counter

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#2129]
I totally forgot the counter component next to the PCI and USB tab during QA, so sorry. 
Is it still possible to add that in the ui? ( @Caleb-Ellis )

![Screen Shot 2021-02-03 at 12.53.29 PM.png](https://images.zenhubusercontent.com/5e6628e0ff9a3ccb84677b2f/ae10364b-1fd6-4a65-92fd-0822fce3d5d4)

**Comment by Caleb-Ellis** [comment]
@amylily1011 Hmm with the current api we would then need to load all the PCI/USB devices even if the user is not on the PCI/USB tabs. Which means no one would ever see the loading state :(

Unless you think the shape of the machine model should be updated with something like:
```
pci_device_count: number,
usb_device_count: number,
```
So that we don't need to load in everything, but this would require a change from the core team.

**Comment by amylily1011** [comment]
@Caleb-Ellis, now worries, in that case we can drop this one. The total number is not important enough to perform this expensive operation :).
