### ISSUE TITLE
Fit long broken messages on machine details

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#2565]
From this discussion: https://github.com/canonical-web-and-design/maas-ui/pull/2561#discussion_r618084767

User's can leave a message when a machine is broken. At the moment it appears truncated with a tooltip with the full message:
<img alt="Screen Shot 2021-04-22 at 3 43 17 pm" width="450" src="https://user-images.githubusercontent.com/361637/115661932-958bae00-a381-11eb-9291-64c65de9956d.png">

As the message can be any length it would be good to find a way to present this info to the user. This is what the full card looks like:

<img alt="Screen Shot 2021-04-22 at 4 56 33 pm" width="1420" src="https://user-images.githubusercontent.com/361637/115795188-c9fb7a80-a412-11eb-80aa-98a8eea26e07.png">

**Comment by amylily1011** [comment]
I think this solution looks great!
I was wondering at first if a user would know that they have to hover over the message, but because the message is not shown in full, it's almost an instinct that we would hover over the message. Is that the real message in the tooltip? @huwshimi  or is it just a mock message 😄 ?

As for this question: `Is this a place where people put a lot of information in real world use?` (@lyubomir-popov )
I really don't know how to answer this question 😂 . But if the question is whether this is the right place to place this message?
From a UX perspective, I think this message is  placed in a very dominant area where users will most likely see it first. So knowing that a machine is marked-broken right away will help them make a decision whether to follow up on what's broken or unmark it. So yes, it's a good placement for machine status.

**Comment by huwshimi** [comment]
> I think this solution looks great!
> I was wondering at first if a user would know that they have to hover over the message, but because the message is not shown in full, it's almost an instinct that we would hover over the message. Is that the real message in the tooltip? @huwshimi or is it just a mock message 😄 ?

The user provides this text when they mark it as broken, so it could be anything.

> As for this question: `Is this a place where people put a lot of information in real world use?` (@lyubomir-popov )
> I really don't know how to answer this question 😂 .

We present the user with a single line input so we're hinting that the text should be short, but users may enter anything into that box:

<img width="1439" alt="Screen Shot 2021-04-26 at 9 52 58 am" src="https://user-images.githubusercontent.com/361637/116013838-8d7b8900-a675-11eb-8c73-3e9446090039.png">

**Comment by lyubomir-popov** [comment]
In that case I agree with @amylily1011, I think the tooltip is a reasonable way to handle this.

If we wanted to be extra sure people will know it is interactive, I would put an info icon after the ellipsis.

**Comment by cristinadresch** [comment]
@huwshimi we can close this right? PR seems closed? https://github.com/canonical-web-and-design/maas-ui/pull/2561

**Comment by huwshimi** [comment]
> @huwshimi we can close this right? PR seems closed? #2561

Yep I think so. Done.
