### ISSUE TITLE
Debugging mass UI

### ISSUE THREAD

**Issue by ipchaube** [canonical-web-and-design/maas-ui#2919]
Hi Their,
Please share if you have some info related to the

- Debugging maas-ui
- Development guide
- Debugging with visual studio

I want this information so that I can start developing new feature with this.

Thank you so much in advance!

**Comment by Caleb-Ellis** [comment]
Hi @ipchaube, you might find our [HACKING.md](https://github.com/canonical-web-and-design/maas-ui/blob/master/HACKING.md) file useful. It should have enough info there to get a MAAS and maas-ui running but please let us know if it's lacking in some way. As for "debugging maas-ui" and "debugging with visual studio" can you clarify what you mean by that?

**Comment by ipchaube** [comment]
HAKING.md is good to run UI but not helping in debugging purposes. 

I mean to How can start all individual components from visual studio code to debug?  Ie proxy, legacy, ui etc.

I am looking best practices to start new feature development with it.

**Comment by Caleb-Ellis** [comment]
Currently we only have the options of running either the full UI (`yarn start`) or just the React workspace (`yarn ui`).

To give a bit of context, we're in the middle of transitioning from angularjs (`legacy`) to React (`ui`). In order to accommodate both an angularjs and React client simultaneously, we use [single-spa](https://single-spa.js.org/) which is found in the `root` workspace. Lastly, the `proxy` workspace just sets up a proxy server for communicating between the MAAS server, `ui`, `legacy` and the development server.

This is all to say that we want to get rid of the `root`, `shared` and `legacy` workspaces as soon as possible, so all new work should be done in `ui`.

Can I ask what sort of new feature you were hoping to develop? Then I might be able to offer some advice on best practices, but "best practices" is a pretty fluid concept generally.

**Comment by ipchaube** [comment]
Thanks

**Comment by ipchaube** [comment]
I am able to debug and run now
