### ISSUE TITLE
No back or close button in white card views

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#397]
![image](https://user-images.githubusercontent.com/2741678/68206616-15269100-ffc5-11e9-9c2a-66d8db1c19d6.png)

**Comment by lyubomir-popov** [comment]
In addition, should you even be able to get to this screen, if the we know none of the OSs you have require a licence key? SHouldn'\t we have an explanation and a disabled add licence key on the previous screen:
![image](https://user-images.githubusercontent.com/2741678/68206714-56b73c00-ffc5-11e9-8c5d-95238a3e5b6d.png)

**Comment by lilyvidenova** [comment]
Nope, the button should just be disabled, with that text as a tooltip.

**Comment by squidsoup** [comment]
> In addition, should you even be able to get to this screen, if we know none of the OSs you have require a licence key? 

I think it can be confusing for users to conditionally hide UI. Better that the user knows that the feature is there (they may not even be aware that MAAS supports Windows Server otherwise), but just leave it disabled until they have a licensed OS image synced. 

Disabling the license key button with a tooltip rather than just displaying an empty card is a good suggestion, thanks!
