### ISSUE TITLE
Refreshing maas-ui displays logo on left edge of screen

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/maas-ui#463]
This logo flashes for a split second before the rest of the content is displayed. Very low priority, but ideally it should display in its correct position within the layout.

![image](https://user-images.githubusercontent.com/2741678/68675019-e96c5380-054e-11ea-8520-9e5f897b99f0.png)

**Comment by Caleb-Ellis** [comment]
This is only an issue in development due to the way webpack-dev-server works (i.e. Hot Module Repacement through JS injection). In production this doesn't happen because the assets are built ahead of time.

There are certainly things we can do, like creating a hard-coded header template specifically for development, but I don't think there's an *elegant* way to solve this while still keeping HMR.

Closing for now.
