### ISSUE TITLE
Default instructions to add rack controller retrieve stale version

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#903]
[LP bug 1864097](https://bugs.launchpad.net/maas/+bug/1864097)

In MAAS 2.7.0, when you click on "Add rack controller" under the "Controllers" tab in the UI, the instructions currently are not complete to guarantee you get the current version of the rack controller.

E.g, if you are installing a second... rack controller, on a clean container or device, and you follow the instructions explicitly, you will likely get an old (2.4.2) rack controller. Postulating that this may be because you have not added the 2.7 ppa to that clean container or device.

Recreate the issue by simply creating a clean lxd container, clicking on "Add rack controller" and following those directions only (without making any other container changes).

**Comment by jurekh** [comment]
Is this issue still reproducible?

**Comment by huwshimi** [comment]
@petermakowski would you mind taking a look and see if you can reproduce this?

**Comment by petermakowski** [comment]
This is still reproducible when you follow instructions for installation from packages. Works fine (installs latest stable version) if you install a snap.

**Comment by petermakowski** [comment]
Let's try and define the work required for solving this issue as comments on launchpad are relating to older versions and are somewhat outdated.

### How this works now
- snap installation will as expected if you're running latest maas as it installs the last available stable version
- if you install the package version you'll most likely get an older version using the instructions as is
- we do mention that users need to make sure `maas-rack-controller` and `maas` versions are the same, but this is probably insufficient and and it would be better if this "just worked".

### What I'd proposing
- suggest using the snap as the first option (instead of as a second choice)
- update instructions for both the snap and package version to include a fixed version that's matching maas ui that's currently running. I'm not sure at this point this could be done without providing extra information from the back-end - something to investigate.
