### ISSUE TITLE
Angular views are displaying as warning icons

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#977]
**Describe the bug**
Angular views are displaying as warning icons. React views work fine.

**MAAS version**
2.8.0~alpha1 (8344-g.b90a00a87)

**LP issue**
N/A

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the project with `dotrun`
2. Open http://0.0.0.0:8400/MAAS/#/machines
3. Check the view matches the screenshot

**Expected behavior**
The machine listing should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/1413534/79236773-502acb80-7e65-11ea-92e5-a7a76c4c0c71.png)

**Additional context**
No errors in the console but the inspector shows whole sections wrapping in warning icons:
![image](https://user-images.githubusercontent.com/1413534/79237147-bca5ca80-7e65-11ea-9f4b-37d34768de83.png)

**Comment by squidsoup** [comment]
Dropping the priority, as this appears to be a dotrun issue.

**Comment by squidsoup** [comment]
Bumping this back to critical as this appears to be manifesting on bolla, so not a dotrun issue.

**Comment by anthonydillon** [comment]
@squidsoup could you take a look at this as priority, please.

**Comment by huwshimi** [comment]
It seems this broke due to a security fix in the latest version of jQuery: http://blog.jquery.com/2020/04/10/jquery-3-5-0-released/.

This slipped through due to a combination of them not using semver so it came through a minor/patch renovate update (https://github.com/canonical-web-and-design/maas-ui/pull/970) and also contained no release notes. I also did not QA this well enough (should have cleaned my local deps).

These are the things we need to do:
- Exclude jQuery from our minor/patch batch renovate config so we review all jQuery updates (as they don't seem to use semver).
- Upgrade jQuery and fix any self closing tags. This will require a pretty thorough QA.
- Backport the jQuery upgrade and tag updates to 2.7.
- Add Cypress integration tests for a logged in React and Angular as canaries to check that pages are being rendered after authentication and websocket connection.

I'll create cards for these issues.

**Comment by mgol** [comment]
@huwshimi Just to clarify a few things: jQuery does generally follow semver since versions 1.11/2.1 (released 6 years ago). We generally do breaking changes only in major version bumps. That said, here we had to patch a security issue which was a result of a fundamental design bug we had to fix on our side. Unfortunately, such a change had to be breaking but we didn't want to leave the 3.x line vulnerable.

We modeled our response by what Node.js does - they had at least one case where they applied a breaking change in a minor version bump because it was required to fix a security issue. Now, the jQuery change was more substantial so I imagine it broke more code than the Node.js breaking minor updates did. As we didn't want to see people blocked from upgrading to jQuery 3.5+, we prepared an upgrade guide at https://jquery.com/upgrade-guide/3.5/ which describes steps to follow to reverse the breaking change while still using a newer jQuery. That does bring the security issue back but it's no worse than just using jQuery 3.4.1 which suffers from this issue.

Sorry for the breakage, we knew it would be painful for some projects but we decided it was the best we could do together with the upgrade guide described above.

A final note: while we try to follow semver as much as we can, jQuery is mostly a DOM library which makes it have quite a big surface area going beyond what's documented in our API docs. Because of that, jQuery updates will always be a bit more risky than updating a bare JS library that has a concrete API which you can fully control. That's why we generally advise to not allow automatic jQuery upgrades in web apps and always verify if the upgrade didn't break anything. Your change in testing strategy makes sense to me.

**Comment by huwshimi** [comment]
@mgol Hey, thanks a lot for taking the time to give us those details. One thing that would have really helped in this case is if the release notes were also published on GitHub with the release (i.e. here https://github.com/jquery/jquery/releases/tag/3.5.0). 

We use Renovate (https://github.com/renovatebot/renovate) to keep our deps up to date and we read through all the release notes that are included in the Renovate PRs. I don't suppose jQuery could publish those release notes there as well?

**Comment by mgol** [comment]
@huwshimi We're thinking about introducing automatically creating a release on GitHub during our release process. In the meantime, I added an entry for 3.5.0 manually at https://github.com/jquery/jquery/releases/tag/3.5.0 that should be clear about the breaking changes. I'll keep that in mind for potential future breaking changes, although it's unlikely they will happen before jQuery 4.0.0, this one was an exception - and in a major update I guess you'd expect breaking changes anyway.

**Comment by huwshimi** [comment]
Thanks @mgol!
